apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: csi-snapshot
spec:
  snapshotClassName: csi-hostpath-ssc
  source:
    name: csi-pvc
    kind: PersistentVolumeClaim